### ISSUE TITLE
Route Search

### ISSUE THREAD

**Issue by BinaryFiddler** [UCSD-CSE-210/Fetch#1]
## Story
As user, 
I want to search for routes to walk my dog 
so that I can have a fun time walking with my dog

### Routes currently in the database
* Mission Regional Trail: In La Jolla, is shaded, no garbage can
* Rose Canyon: In La Jolla, not shaded, no garbage can
* Doyle Park: In La Jolla, Not shaded, no garbage can

### Scenario 1
Given the database above
When the user searches for a shaded route in La Jolla
Then the user is shown Mission Trail

### Scenario 2
Given the database above
When the user searches for a not shaded route  in La Jolla
Then the user is shown Doyle Park and Rose Canyon

![IMG_2361.JPG](https://images.zenhubusercontent.com/59f7a3a68a75884b9085643f/b8238bcb-8a5b-4f1d-9e52-11a1e46fd487)

![Image uploaded from iOS.jpg](https://images.zenhubusercontent.com/59f7a3a68a75884b9085643f/0f0a3051-63e4-4f3f-b440-8a0f351affab)

![Image uploaded from iOS.jpg](https://images.zenhubusercontent.com/59f7a3a68a75884b9085643f/e09646ed-f87a-4995-9c64-85374e1daf67)

**Comment by soelgary** [comment]
### Search UI

- [ ] Search bar (location)
- [ ] Checkboxes for boolean values (water, poop bags, shade, garbage cans, off road vs road, etc.)
- [ ] Render search results

### Search Backend

- [ ] Build search over index
- [ ] Expose search API

**Comment by huang-chenyu** [comment]
[Uploading... IMG_2361.JPG ]

**Comment by huang-chenyu** [comment]
![IMG_2361.JPG](https://images.zenhubusercontent.com/59f7a3a68a75884b9085643f/8749a57a-f46b-4587-948b-ab518f6894fd)

**Comment by huang-chenyu** [comment]
![IMG_2361.JPG](https://images.zenhubusercontent.com/59f7a3a68a75884b9085643f/b8238bcb-8a5b-4f1d-9e52-11a1e46fd487)

**Comment by huang-chenyu** [comment]
![Image uploaded from iOS.jpg](https://images.zenhubusercontent.com/59f7a3a68a75884b9085643f/e09646ed-f87a-4995-9c64-85374e1daf67)

**Comment by huang-chenyu** [comment]
![Image uploaded from iOS.jpg](https://images.zenhubusercontent.com/59f7a3a68a75884b9085643f/0f0a3051-63e4-4f3f-b440-8a0f351affab)
